Repository TheBevyFlock/bevy_cli, pull requests merged in 2024-09, with the labels that each got.

#27 chore: remove `Cargo.lock` from the `gitignore`
  .gitignore
  Cargo.lock
Labels: C-Code-Quality

#25 Separate backend and CLI
  Cargo.toml
  src/bin/lint_driver.rs
  src/bin/main.rs
  src/lib.rs
  src/main.rs
  src/template.rs
Labels: C-Code-Quality, A-Cross-Cutting

#28 chore: update README to include instructions to manually install rustc components
  README.md
Labels: C-Docs, C-Code-Quality, A-Cross-Cutting

#30 Remove direct dependency on `bevy_lint` from `bevy_cli`
  Cargo.lock
  Cargo.toml
  bevy_lint/Cargo.toml
  bevy_lint/src/bin/driver.rs
  bevy_lint/src/bin/main.rs
  bevy_lint/src/driver.rs
  bevy_lint/src/lib.rs
  src/bin/lint_driver.rs
  src/bin/main.rs
  src/lint.rs
Labels: A-CLI, A-Linter, C-Code-Quality, C-Usability

#29 Small changes to manual component installation instructions
  README.md
  rust-toolchain.toml
Labels: C-Docs, A-Cross-Cutting

#67 Forward arguments from `bevy lint` to `cargo check`
  bevy_lint/src/bin/main.rs
Labels: A-Linter, C-Enhancement

#72 Add ArgBuilder utility to make it easier to construct command arguments
  src/external_cli/arg_builder.rs
  src/external_cli/mod.rs
  src/lib.rs
Labels: A-CLI, C-Code-Quality

#73 Add wrapper for rustup command
  Cargo.lock
  Cargo.toml
  src/external_cli/mod.rs
  src/external_cli/rustup.rs
Labels: A-CLI, C-Enhancement

#74 Bump `gix-path`
  Cargo.lock
Labels: C-Dependencies, A-Cross-Cutting

#82 Allow 2d as a template value for quickstart
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/template.rs
Labels: C-Usability, A-Templates

#84 Add lint: `bevy::main_return_without_appexit`
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/src/callback.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/paths.rs
Labels: A-Linter, C-Enhancement

#75 Add wrapper for wasm_bindgen CLI
  src/external_cli/mod.rs
  src/external_cli/wasm_bindgen.rs
Labels: A-CLI, C-Enhancement

#76 Add wrapper for cargo build command
  src/external_cli/cargo/build.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/mod.rs
Labels: A-CLI, C-Enhancement

#93 Return `cargo`'s exit code on failure in `bevy_lint`
  bevy_lint/src/bin/main.rs
Labels: A-Linter, C-Enhancement

#86 Add lint: `bevy::insert_event_resource`
  bevy_lint/src/lib.rs
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/paths.rs
Labels: A-Linter, C-Enhancement

#98 Create lint groups
  bevy_lint/src/callback.rs
  bevy_lint/src/groups.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/mod.rs
Labels: A-Linter, C-Usability

#106 Actually *register* the lint groups
  bevy_lint/src/callback.rs
  bevy_lint/src/groups.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/mod.rs
Labels: A-Linter, C-Bug

#110 Add basic support for cargo metadata
  Cargo.lock
  Cargo.toml
  src/external_cli/cargo/metadata.rs
  src/external_cli/cargo/mod.rs
Labels: A-CLI, C-Enhancement

#95 Add lint: `panicking_query_methods` and `panicking_world_methods`
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/src/paths.rs
Labels: A-Linter, C-Feature

#103 Add a wrapper for cargo run
  src/external_cli/cargo/mod.rs
  src/external_cli/cargo/run.rs
Labels: A-CLI, C-Feature

#116 Handle empty value lists for `ArgBuilder::add_value_list`
  src/external_cli/arg_builder.rs
Labels: C-Bug

#102 Bevy build
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
  src/build/args.rs
  src/build/mod.rs
  src/external_cli/cargo/install.rs
  src/external_cli/cargo/metadata.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/mod.rs
  src/external_cli/rustup.rs
  src/external_cli/wasm_bindgen.rs
  src/lib.rs
  src/manifest.rs
Labels: A-CLI, C-Feature
