Repository TheBevyFlock/bevy_cli, pull requests merged in 2024-10, with the labels that each got.

#121 Bug fixing and chores related to linting
  .github/workflows/ci.yml
  Cargo.lock
  README.md
  bevy_lint/Cargo.toml
  bevy_lint/build.rs
  bevy_lint/src/bin/main.rs
  rust-toolchain.toml
  src/external_cli/cargo/run.rs
Labels: A-Linter, C-Bug, C-Usability

#120 Bevy run
  Cargo.lock
  Cargo.toml
  assets/web/index.html
  src/bin/main.rs
  src/external_cli/cargo/run.rs
  src/external_cli/wasm_bindgen.rs
  src/lib.rs
  src/run/args.rs
  src/run/mod.rs
  src/run/serve.rs
Labels: A-CLI, C-Feature

#111 Add lint: Plugin not ending in "Plugin"
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
  bevy_lint/src/paths.rs
Labels: A-Linter, C-Feature

#124 Improve lint driver entrypoint
  bevy_lint/src/bin/driver.rs
Labels: A-Linter, C-Usability

#126 Replace `lower_ty()` with `typeck_results.node_type()`
  bevy_lint/src/lib.rs
  bevy_lint/src/lints/insert_event_resource.rs
Labels: A-Linter, C-Bug

#134 Warn on `rustc::internal` lints
  bevy_lint/src/lib.rs
Labels: A-Linter, C-Code-Quality

#125 Implement UI testing framework
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/tests/ui.rs
  bevy_lint/tests/ui/main_return_without_appexit.rs
  bevy_lint/tests/ui/main_return_without_appexit.stderr
Labels: A-Linter, C-Testing

#128 Add UI tests for existing lints
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/tests/ui/insert_event_resource/bug_94.rs
  bevy_lint/tests/ui/insert_event_resource/main.fixed
  bevy_lint/tests/ui/insert_event_resource/main.rs
  bevy_lint/tests/ui/insert_event_resource/main.stderr
  bevy_lint/tests/ui/main_return_without_appexit/bug_132.rs
  bevy_lint/tests/ui/main_return_without_appexit/bug_132.stderr
  bevy_lint/tests/ui/main_return_without_appexit/bug_87.rs
  bevy_lint/tests/ui/main_return_without_appexit/bug_87.stderr
  bevy_lint/tests/ui/main_return_without_appexit/bug_94.rs
  bevy_lint/tests/ui/main_return_without_appexit/main.rs
  bevy_lint/tests/ui/main_return_without_appexit/main.stderr
  bevy_lint/tests/ui/main_return_without_appexit/muted_function.rs
  bevy_lint/tests/ui/main_return_without_appexit/return_appexit.rs
  bevy_lint/tests/ui/main_return_without_appexit/return_result.rs
  bevy_lint/tests/ui/main_return_without_appexit/return_unit.rs
  bevy_lint/tests/ui/main_return_without_appexit/return_unit.stderr
  bevy_lint/tests/ui/panicking_methods/query.rs
  bevy_lint/tests/ui/panicking_methods/query.stderr
  bevy_lint/tests/ui/panicking_methods/query_state.rs
  bevy_lint/tests/ui/panicking_methods/query_state.stderr
  bevy_lint/tests/ui/panicking_methods/world.rs
  bevy_lint/tests/ui/panicking_methods/world.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/bug_132.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/bug_132.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/main.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/main.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/spoofed_name.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/spoofed_name.stderr
Labels: A-Linter, C-Testing

#140 Setup Typos in CI
  .github/workflows/ci.yml
  src/external_cli/cargo/metadata.rs
Labels: A-CI, C-Feature

#149 Fix ICE when checking `bevy_reflect`
  bevy_lint/src/lints/missing_reflect.rs
Labels: A-Linter, C-Bug

#147 Lint documentation improvements
  bevy_lint/src/callback.rs
  bevy_lint/src/groups.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/mod.rs
Labels: A-Linter, C-Docs

#144 Fix loading screen for default Bevy app
  assets/web/index.html
Labels: C-Bug, A-Run

#142 Improve binary package detection for `bevy run`
  src/build/mod.rs
  src/external_cli/cargo/metadata.rs
  src/run/mod.rs
Labels: C-Usability, A-Run

#153 Rustup to `nightly-2024-08-21`
  Cargo.lock
  bevy_lint/Cargo.toml
  rust-toolchain.toml
Labels: A-Linter, C-Dependencies

#151 Support `run_schedule()` in `panicking_world_methods` lint
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/tests/ui/panicking_methods/world.rs
  bevy_lint/tests/ui/panicking_methods/world.stderr
Labels: A-Linter, C-Feature

#154 Enable fuzzy-searching for dependency crates in VSCode
  .vscode/settings.json
Labels: C-Usability, A-Cross-Cutting

#162 Make lint silence locations more intuitive
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
  bevy_lint/tests/ui/main_return_without_appexit/bug_132.rs
  bevy_lint/tests/ui/main_return_without_appexit/bug_132.stderr
  bevy_lint/tests/ui/main_return_without_appexit/muted.rs
  bevy_lint/tests/ui/main_return_without_appexit/muted_function.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/bug_132.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/bug_132.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/main.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/main.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/spoofed_name.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/spoofed_name.stderr
Labels: A-Linter, C-Bug

#160 Publish `bevy_lint` docs to Github Pages
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/extract-rust-version.yml
Labels: A-CI, A-Linter, C-Docs

#159 Add `CONTRIBUTING.md` for CLI
  CONTRIBUTING.md
  README.md
Labels: A-CLI, C-Docs

#163 Write `bevy_lint` release checklist and changelog
  Cargo.lock
  bevy_lint/CHANGELOG.md
  bevy_lint/docs/release.md
Labels: A-Linter, C-Docs

#166 Clarify `release.md` and add compatibility table
  bevy_lint/README.md
  bevy_lint/docs/release.md
Labels: A-Linter, C-Docs
