Repository TheBevyFlock/bevy_cli, pull requests merged in 2025-04, with the labels that each got.

#340 Update CLI to 2024 edition
  Cargo.toml
  src/external_cli/arg_builder.rs
  src/external_cli/cargo/build.rs
  src/external_cli/cargo/install.rs
  src/external_cli/cargo/metadata.rs
  src/external_cli/cargo/run.rs
  src/external_cli/mod.rs
  src/external_cli/wasm_bindgen.rs
  src/lint.rs
  src/web/bin_target.rs
  src/web/build.rs
  src/web/run.rs
  src/web/serve.rs
Labels: A-CLI, D-Trivial, S-Needs-Review

#342 CLI: Bump to `cargo-generate` v0.23.0
  Cargo.lock
  Cargo.toml
Labels: C-Dependencies, A-Templates, D-Trivial

#349 Bump dependencies in lockfile
  Cargo.lock
Labels: C-Dependencies, A-Cross-Cutting, D-Trivial, S-Needs-Review

#357 Cleanup `panicking_methods` lint and run `cargo update`
  Cargo.lock
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/paths.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
  tests/bevy_cli_test/Cargo.lock
Labels: A-Linter, C-Docs, C-Code-Quality, D-Trivial, S-Needs-Review

#359 Only log headers if any are added
  src/web/serve.rs
Labels: A-Run, A-Web, D-Trivial, S-Needs-Review

#363 Small fixups to the `bevy_lint` README
  bevy_lint/README.md
Labels: A-Linter, C-Docs, D-Trivial, S-Needs-Review

#371 pass `args.is_web()` to `CliConfig::for_package()`
  src/build/mod.rs
  src/config.rs
  src/run/mod.rs
Labels: C-Bug, A-Web, D-Trivial

#373 Bump Rust toolchain to `nightly-2025-04-03`
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
  bevy_lint/src/utils/hir_parse.rs
  rust-toolchain.toml
  src/external_cli/cargo/metadata.rs
Labels: A-Linter, C-Docs, D-Straightforward, S-Needs-Review

#358 Optimistic command execution
  src/bin_target.rs
  src/build/args.rs
  src/build/mod.rs
  src/external_cli/cargo/install.rs
  src/external_cli/cargo/metadata.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/mod.rs
  src/external_cli/rustup.rs
  src/external_cli/wasm_bindgen.rs
  src/external_cli/wasm_opt.rs
  src/lint.rs
  src/run/args.rs
  src/run/mod.rs
  src/web/build.rs
Labels: A-CLI, C-Code-Quality, C-Usability, D-Complex, S-Needs-Review, C-Performance

#351 CLI: Support configuring rustflags in Cargo.toml
  src/build/args.rs
  src/config.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/mod.rs
  src/run/args.rs
  src/run/mod.rs
  src/web/build.rs
Labels: A-CLI, C-Feature, D-Straightforward, S-Needs-Review

#376 Allow forwarding of args to underlying program
  src/external_cli/arg_builder.rs
  src/run/args.rs
Labels: C-Feature, A-Run, D-Straightforward, S-Needs-Review

#379 Fix running web app with bundle option
  src/web/bundle.rs
  src/web/serve.rs
Labels: C-Bug, A-Run, A-Web, S-Needs-Review

#375 Improve logging of bevy_cli config
  Cargo.toml
  src/build/args.rs
  src/config.rs
  src/run/args.rs
Labels: A-CLI, C-Usability, D-Straightforward, S-Needs-Review

#378 Improve error message for failed `cargo metadata`
  src/external_cli/cargo/metadata.rs
  src/external_cli/mod.rs
Labels: A-CLI, C-Usability, D-Straightforward

#345 Add lint: unconventional_naming
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/style/mod.rs
  bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/style/unconventional_naming.rs
  bevy_lint/src/paths.rs
  bevy_lint/src/utils/hir_parse.rs
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/main.stderr
  bevy_lint/tests/ui/plugin_not_ending_in_plugin/spoofed_name.stderr
  bevy_lint/tests/ui/unconventional_naming/plugin.rs
  bevy_lint/tests/ui/unconventional_naming/plugin.stderr
  bevy_lint/tests/ui/unconventional_naming/spoofed_name.rs
  bevy_lint/tests/ui/unconventional_naming/spoofed_name.stderr
  bevy_lint/tests/ui/unconventional_naming/system_set.rs
  bevy_lint/tests/ui/unconventional_naming/system_set.stderr
Labels: A-Linter, C-Feature, S-Needs-Review

#381 Clarify that only repos from "TheBevyFlock" are usable via shortcut
  src/bin/main.rs
Labels: C-Docs, A-Templates, D-Trivial

#377 Refactor `LintGroup` into a trait
  bevy_lint/src/callback.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/cargo.rs
  bevy_lint/src/lints/complexity/mod.rs
  bevy_lint/src/lints/correctness/mod.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/nursery/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/nursery/mod.rs
  bevy_lint/src/lints/nursery/zst_query.rs
  bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
  bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
  bevy_lint/src/lints/pedantic/mod.rs
  bevy_lint/src/lints/performance/mod.rs
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/lints/restriction/mod.rs
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/lints/style/mod.rs
  bevy_lint/src/lints/style/unconventional_naming.rs
  bevy_lint/src/lints/suspicious/insert_event_resource.rs
  bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
  bevy_lint/src/lints/suspicious/iter_current_update_events.rs
  bevy_lint/src/lints/suspicious/mod.rs
Labels: A-Linter, C-Code-Quality, D-Modest, S-Needs-Review

#387 Improve the docs for `unconventional_naming`
  bevy_lint/src/lints/style/unconventional_naming.rs
Labels: A-Linter, C-Docs, D-Trivial, S-Needs-Review

#380 Create action to install linter
  .github/workflows/linter-action.yml
  bevy_lint/README.md
  bevy_lint/action.yml
  bevy_lint/docs/how-to/bump-rust.md
  bevy_lint/docs/how-to/release.md
Labels: A-CI, A-Linter, C-Feature, D-Modest, S-Needs-Review

#391 Mark `plugin_not_ending_in_plugin` as a renamed lint
  bevy_lint/src/lints/style/mod.rs
Labels: A-Linter, C-Usability, D-Trivial, S-Needs-Review

#396 Linter: Update dev dependencies
  Cargo.lock
  bevy_lint/Cargo.toml
Labels: A-Linter, C-Dependencies, D-Trivial, S-Needs-Review

#389 Lint: `missing_reflect` check if all fields implement `Reflect` otherwise `Applicability ::MaybeIncorrect`
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/paths.rs
  bevy_lint/tests/ui/missing_reflect/bug_141.rs
  bevy_lint/tests/ui/missing_reflect/bug_141.stderr
  bevy_lint/tests/ui/missing_reflect/derived.fixed
  bevy_lint/tests/ui/missing_reflect/impl.fixed
  bevy_lint/tests/ui/missing_reflect/impl_ref.fixed
  bevy_lint/tests/ui/missing_reflect/none_reflect_fields.rs
  bevy_lint/tests/ui/missing_reflect/none_reflect_fields.stderr
Labels: A-Linter, C-Usability, S-Needs-Review

#392 Release linter v0.3.0
  Cargo.lock
  bevy_lint/CHANGELOG.md
  bevy_lint/Cargo.toml
  bevy_lint/MIGRATION.md
  bevy_lint/README.md
  bevy_lint/action.yml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
Labels: A-Linter, C-Docs
