Repository TheBevyFlock/bevy_cli, pull requests merged in 2025-03, with the labels that each got.

#295 switch to axum
  Cargo.lock
  Cargo.toml
  src/run/serve.rs
Labels: C-Dependencies, A-Web, S-Needs-Review

#297 Guard web functionality behind a feature flag
  .github/workflows/ci.yml
  Cargo.toml
  src/build/args.rs
  src/build/mod.rs
  src/external_cli/cargo/install.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/mod.rs
  src/external_cli/wasm_bindgen.rs
  src/lib.rs
  src/run/args.rs
  src/run/mod.rs
  src/web/bin_target.rs
  src/web/build.rs
  src/web/bundle.rs
  src/web/mod.rs
  src/web/run.rs
  src/web/serve.rs
  src/web/wasm_opt.rs
Labels: C-Dependencies, A-Web, D-Modest, S-Needs-Review

#290 Log invocations of external commands
  src/bin/main.rs
  src/build/mod.rs
  src/external_cli/cargo/build.rs
  src/external_cli/cargo/install.rs
  src/external_cli/cargo/metadata.rs
  src/external_cli/cargo/run.rs
  src/external_cli/mod.rs
  src/external_cli/rustup.rs
  src/external_cli/wasm_bindgen.rs
  src/lint.rs
  src/run/mod.rs
  src/web/build.rs
Labels: A-CLI, S-Needs-Review

#306 Bump to a newer version of `ui_test`
  Cargo.lock
  Cargo.toml
  bevy_lint/Cargo.toml
Labels: A-Linter, C-Dependencies, D-Trivial, S-Needs-Review

#308 Release `bevy_lint` v0.2.0
  Cargo.lock
  bevy_lint/CHANGELOG.md
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/src/lints/cargo.rs
  bevy_lint/src/lints/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/mod.rs
Labels: A-Linter

#312 Post-release v0.2.0
  Cargo.lock
  bevy_lint/CHANGELOG.md
  bevy_lint/Cargo.toml
  bevy_lint/README.md
Labels: A-Linter

#315 Ignore `bevy new` integration tests by default
  tests/new.rs
Labels: A-Templates, D-Trivial, S-Needs-Review

#317 Add note in `MethodCall::receiver` docs that it may include the reference
  bevy_lint/src/utils/hir_parse.rs
Labels: A-Linter, C-Docs, D-Trivial, S-Needs-Review

#314 Create `iter_current_update_events` lint
  bevy_lint/CHANGELOG.md
  bevy_lint/docs/how-to/types.md
  bevy_lint/src/lints/iter_current_update_events.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/tests/ui/iter_current_update_events/plain.rs
  bevy_lint/tests/ui/iter_current_update_events/plain.stderr
  bevy_lint/tests/ui/iter_current_update_events/res.rs
  bevy_lint/tests/ui/iter_current_update_events/res.stderr
Labels: A-Linter, C-Feature, D-Straightforward, S-Needs-Review

#321 Move lints into submodules for each lint group
  bevy_lint/src/lints/cargo.rs
  bevy_lint/src/lints/complexity/mod.rs
  bevy_lint/src/lints/correctness/mod.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/nursery/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/nursery/mod.rs
  bevy_lint/src/lints/nursery/zst_query.rs
  bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
  bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
  bevy_lint/src/lints/pedantic/mod.rs
  bevy_lint/src/lints/performance/mod.rs
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/lints/restriction/mod.rs
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/lints/style/mod.rs
  bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/suspicious/insert_event_resource.rs
  bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
  bevy_lint/src/lints/suspicious/iter_current_update_events.rs
  bevy_lint/src/lints/suspicious/mod.rs
Labels: A-Linter, C-Docs, C-Usability

#263 Handle macros in lints
  bevy_lint/src/lints/nursery/zst_query.rs
  bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
  bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/suspicious/insert_event_resource.rs
  bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
Labels: A-Linter, C-Usability, S-Needs-Review

#326 Use direct field access instead of `HasSession` trait
  bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/suspicious/insert_event_resource.rs
  bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
Labels: A-Linter, D-Trivial, S-Needs-Review

#330 Don't install Linux dependencies twice in CI
  .github/workflows/ci.yml
Labels: A-CI, C-Bug, D-Trivial, S-Needs-Review

#316 Enable internal `rustc` lints
  .github/workflows/ci.yml
  bevy_lint/src/lib.rs
  bevy_lint/src/lints/nursery/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/nursery/zst_query.rs
Labels: A-CI, A-Linter, C-Code-Quality, D-Straightforward, S-Needs-Review

#328 Move lint group definitons and docs to `crate::lints`
  bevy_lint/README.md
  bevy_lint/src/callback.rs
  bevy_lint/src/config.rs
  bevy_lint/src/groups.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/complexity/mod.rs
  bevy_lint/src/lints/correctness/mod.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/nursery/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/nursery/mod.rs
  bevy_lint/src/lints/nursery/zst_query.rs
  bevy_lint/src/lints/pedantic/borrowed_reborrowable.rs
  bevy_lint/src/lints/pedantic/main_return_without_appexit.rs
  bevy_lint/src/lints/pedantic/mod.rs
  bevy_lint/src/lints/performance/mod.rs
  bevy_lint/src/lints/restriction/missing_reflect.rs
  bevy_lint/src/lints/restriction/mod.rs
  bevy_lint/src/lints/restriction/panicking_methods.rs
  bevy_lint/src/lints/style/mod.rs
  bevy_lint/src/lints/style/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/suspicious/insert_event_resource.rs
  bevy_lint/src/lints/suspicious/insert_unit_bundle.rs
  bevy_lint/src/lints/suspicious/iter_current_update_events.rs
  bevy_lint/src/lints/suspicious/mod.rs
  bevy_lint/src/utils/mod.rs
Labels: A-Linter, C-Docs, C-Code-Quality, C-Usability, D-Straightforward, S-Needs-Review

#287 CLI: Make rustup optional
  Cargo.toml
  src/external_cli/cargo/install.rs
  src/external_cli/mod.rs
  src/external_cli/rustup.rs
  src/web/build.rs
Labels: A-CLI, D-Straightforward, S-Needs-Testing
