Repository TheBevyFlock/bevy_cli, pull requests merged in 2025-01, with the labels that each got.

#191 Linter: Support Bevy 0.15
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/src/paths.rs
  bevy_lint/tests/ui/borrowed_reborrowable/entity_commands.stderr
  bevy_lint/tests/ui/missing_reflect/impl.rs
  bevy_lint/tests/ui/missing_reflect/impl.stderr
  bevy_lint/tests/ui/missing_reflect/impl_ref.rs
  bevy_lint/tests/ui/missing_reflect/impl_ref.stderr
  bevy_lint/tests/ui/panicking_methods/world.rs
  bevy_lint/tests/ui/panicking_methods/world.stderr
Labels: A-Linter, C-Dependencies, C-Breaking-Change

#215 Bump linter to `nightly-2025-01-09`
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/docs/README.md
  bevy_lint/docs/how-to/bump-rust.md
  bevy_lint/src/bin/driver.rs
  rust-toolchain.toml
Labels: A-Linter, C-Dependencies

#219 Fix determining artifact folder for dev profile
  src/external_cli/cargo/mod.rs
  src/run/mod.rs
Labels: C-Bug, A-Run, A-Build, D-Straightforward, P-High

#220 Update linter install link and fix `declare_bevy_lint!` visibility
  bevy_lint/src/lint.rs
  src/lint.rs
Labels: A-CLI, A-Linter, C-Docs, C-Usability

#223 Add documentation for web commands to README
  README.md
Labels: C-Docs, A-Run, A-Build, A-Web, D-Trivial

#231 De-duplicate web build code
  src/bin/main.rs
  src/build/mod.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/cargo/run.rs
  src/run/args.rs
  src/run/mod.rs
  src/web/bundle.rs
Labels: C-Code-Quality, A-Run, A-Build, A-Web, D-Straightforward

#228 Extend `declare_lint_pass!` macro
  bevy_lint/src/lib.rs
  bevy_lint/src/lint.rs
  bevy_lint/src/lints/borrowed_reborrowable.rs
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/missing_reflect.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/zst_query.rs
Labels: A-Linter, C-Usability

#209 Add support for `cargo`'s `--config` arg
  src/bin/main.rs
  src/build/mod.rs
  src/external_cli/arg_builder.rs
  src/external_cli/cargo/build.rs
  src/external_cli/cargo/mod.rs
  src/external_cli/cargo/run.rs
  src/run/args.rs
  src/run/mod.rs
  src/web/profiles.rs
Labels: C-Feature, A-Run, A-Build, D-Straightforward, S-Needs-Review

#235 Improve error message when showing prompt in non-interactive shell
  src/external_cli/cargo/install.rs
  src/external_cli/rustup.rs
Labels: C-Usability, A-Run, A-Build, S-Needs-Review

#244 Add linter section to CLI `README.md`
  README.md
Labels: A-CLI, C-Docs, S-Needs-Review

#243 add `bevy new` use facing documentation
  README.md
Labels: A-CLI, C-Docs, S-Needs-Review

#222 Add E2E tests for `bevy build`
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  tests/bevy_cli_test/Cargo.lock
  tests/bevy_cli_test/Cargo.toml
  tests/bevy_cli_test/bevy_default/Cargo.toml
  tests/bevy_cli_test/bevy_default/src/main.rs
  tests/build.rs
Labels: A-CI, C-Testing, A-Build, D-Modest, S-Needs-Review

#210 Lint against inserting () as a component
  bevy_lint/src/lints/insert_unit_bundle.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/tests/ui/insert_unit_bundle/bug_248.rs
  bevy_lint/tests/ui/insert_unit_bundle/bug_248.stderr
  bevy_lint/tests/ui/insert_unit_bundle/main.rs
  bevy_lint/tests/ui/insert_unit_bundle/main.stderr
  bevy_lint/tests/ui/insert_unit_bundle/muted.rs
  bevy_lint/tests/ui/insert_unit_bundle/spawn_empty.fixed
  bevy_lint/tests/ui/insert_unit_bundle/spawn_empty.rs
  bevy_lint/tests/ui/insert_unit_bundle/spawn_empty.stderr
Labels: A-Linter, C-Feature, X-Uncontroversial, S-Needs-Review

#249 Fix audio context not restarting automatically
  assets/web/index.html
Labels: C-Bug, A-Run, A-Web, D-Trivial
