Repository TheBevyFlock/bevy_cli, pull requests merged in 2025-02, with the labels that each got.

#251 `Cargo.toml` linter configuration
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/src/callback.rs
  bevy_lint/src/config.rs
  bevy_lint/src/lib.rs
  bevy_lint/src/utils/cargo.rs
  bevy_lint/src/utils/mod.rs
Labels: A-Linter, C-Feature, C-Usability, X-Blessed, S-Needs-Review

#255 Add cache for test workspace
  .github/workflows/ci.yml
Labels: A-CI, D-Straightforward, S-Needs-Testing

#256 Refresh web page when server restarts
  Cargo.lock
  Cargo.toml
  assets/web/_bevy_dev/auto_reload.js
  src/run/serve.rs
Labels: C-Feature, A-Run, A-Web, D-Modest, S-Needs-Review

#257 Linter: Add support for `--version` flag
  bevy_lint/src/bin/main.rs
Labels: A-Linter, C-Usability, D-Trivial, S-Needs-Review

#259 Bump `openssl` and fix CI on Windows
  Cargo.lock
  bevy_lint/src/bin/main.rs
Labels: C-Dependencies, A-Cross-Cutting, P-High

#261 Lower `zst_query` to be a nursery lint
  bevy_lint/src/lints/zst_query.rs
Labels: A-Linter, C-Bug, D-Trivial, S-Needs-Review

#253 check against alternative method syntax
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/insert_unit_bundle.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/src/utils/hir_parse.rs
  bevy_lint/tests/ui/insert_event_resource/bug_94.rs
  bevy_lint/tests/ui/insert_event_resource/main.fixed
  bevy_lint/tests/ui/insert_event_resource/main.rs
  bevy_lint/tests/ui/insert_event_resource/main.stderr
  bevy_lint/tests/ui/insert_unit_bundle/main.rs
  bevy_lint/tests/ui/insert_unit_bundle/main.stderr
  bevy_lint/tests/ui/main_return_without_appexit/bug_94.rs
  bevy_lint/tests/ui/main_return_without_appexit/main.rs
  bevy_lint/tests/ui/main_return_without_appexit/main.stderr
  bevy_lint/tests/ui/panicking_methods/query.rs
  bevy_lint/tests/ui/panicking_methods/query.stderr
  bevy_lint/tests/ui/panicking_methods/query_state.rs
  bevy_lint/tests/ui/panicking_methods/query_state.stderr
  bevy_lint/tests/ui/panicking_methods/world.rs
  bevy_lint/tests/ui/panicking_methods/world.stderr
Labels: A-Linter, C-Bug, S-Needs-Review

#260 Make errors more informative when cargo metadata fails
  src/external_cli/cargo/metadata.rs
Labels: A-CLI, C-Usability, S-Waiting-on-Author

#264 Don't use `cargo +TOOLCHAIN` shortcut and move `--cfg bevy_lint` logic
  bevy_lint/src/bin/main.rs
  bevy_lint/src/callback.rs
Labels: A-Linter, C-Usability, D-Trivial, S-Needs-Review

#270 Add link to full list of lints in `README.md`
  bevy_lint/README.md
Labels: A-Linter, C-Docs, D-Trivial, S-Needs-Review

#266 Simplify `locate_manifest()`
  bevy_lint/src/utils/cargo.rs
Labels: A-Linter, C-Code-Quality

#265 Add Shell-Completion Auto-generation
  Cargo.lock
  Cargo.toml
  src/bin/main.rs
Labels: A-CLI, C-Feature, D-Straightforward, S-Needs-Review

#271 Merge `panicking_query_methods` and `panicking_world_methods`
  bevy_lint/src/lints/mod.rs
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/tests/ui/panicking_methods/query.rs
  bevy_lint/tests/ui/panicking_methods/query.stderr
  bevy_lint/tests/ui/panicking_methods/query_state.rs
  bevy_lint/tests/ui/panicking_methods/query_state.stderr
  bevy_lint/tests/ui/panicking_methods/world.rs
  bevy_lint/tests/ui/panicking_methods/world.stderr
Labels: A-Linter, C-Usability, C-Breaking-Change, S-Needs-Review

#278 Bump linter to `nightly-2025-02-20` and Rust 2024
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/README.md
  bevy_lint/docs/README.md
  bevy_lint/docs/how-to/types.md
  bevy_lint/src/bin/driver.rs
  bevy_lint/src/bin/main.rs
  bevy_lint/src/lints/borrowed_reborrowable.rs
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/missing_reflect.rs
  bevy_lint/src/lints/panicking_methods.rs
  bevy_lint/src/lints/plugin_not_ending_in_plugin.rs
  bevy_lint/src/lints/zst_query.rs
  bevy_lint/src/utils/hir_parse.rs
  bevy_lint/tests/ui.rs
  bevy_lint/tests/ui/insert_event_resource/main.stderr
  rust-toolchain.toml
  tests/bevy_cli_test/Cargo.lock
Labels: A-Linter, C-Dependencies, C-Docs, C-Code-Quality, D-Straightforward, S-Needs-Review

#280 Duplicate bevy deps
  .github/workflows/ci.yml
  Cargo.lock
  bevy_lint/Cargo.toml
  bevy_lint/src/lints/cargo/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/cargo/mod.rs
  bevy_lint/src/lints/mod.rs
  bevy_lint/tests/test_utils/mod.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.stderr
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.stderr
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.stderr
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/src/main.rs
  bevy_lint/tests/ui.rs
  bevy_lint/tests/ui_cargo.rs
Labels: A-Linter, C-Feature

#276 Create specification for lint module docs in contributing guide
  bevy_lint/docs/README.md
  bevy_lint/docs/reference/lint-module-docs.md
  bevy_lint/src/lints/borrowed_reborrowable.rs
  bevy_lint/src/lints/cargo/duplicate_bevy_dependencies.rs
  bevy_lint/src/lints/cargo/mod.rs
  bevy_lint/src/lints/insert_event_resource.rs
  bevy_lint/src/lints/insert_unit_bundle.rs
  bevy_lint/src/lints/main_return_without_appexit.rs
  bevy_lint/src/lints/missing_reflect.rs
  bevy_lint/src/lints/zst_query.rs
Labels: A-Linter, C-Docs, S-Needs-Review

#281 Force rustup to add `rustc_driver.dll` to the `PATH`
  bevy_lint/src/bin/main.rs
Labels: A-Linter, C-Bug, S-Needs-Review

#273 Automatically add a sensible title to web page
  assets/web/index.html
  src/run/mod.rs
  src/run/serve.rs
  src/web/bundle.rs
Labels: C-Feature, A-Web, D-Modest, S-Needs-Review

#282 switch to `tracing`
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/main.rs
  src/build/mod.rs
  src/external_cli/rustup.rs
  src/run/mod.rs
  src/web/bundle.rs
  src/web/wasm_opt.rs
Labels: A-CLI, C-Usability, X-Blessed, S-Needs-Review

#288 v0.2.0 changelog, migration guide, and other small changes
  bevy_lint/CHANGELOG.md
  bevy_lint/MIGRATION.md
  bevy_lint/README.md
  bevy_lint/docs/how-to/release.md
  bevy_lint/src/bin/main.rs
Labels: A-Linter, C-Docs, D-Trivial, S-Needs-Review

#291 Improve CI speeds
  Cargo.lock
  Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.stderr
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/fail/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/long_version_format/pass/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/short_version_format/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.stderr
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/fail/src/main.rs
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/Cargo.lock
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/Cargo.toml
  bevy_lint/tests/ui-cargo/duplicate_bevy_dependencies/with_feature/pass/src/main.rs
  tests/bevy_cli_test/Cargo.lock
  tests/bevy_cli_test/bevy_default/Cargo.toml
Labels: A-CI, S-Needs-Review, C-Performance
